version: '3.8'

services:
  db:
    image: mysql:8.0
    restart: unless-stopped
    container_name: db
    ports:
      - 3307:3306
    environment:
      - MYSQL_DATABASE=articles
      - MYSQL_ROOT_PASSWORD=asd3311062
      - MYSQL_PASSWORD=asd3311062
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - app

  laravel-app:
    restart: unless-stopped
    networks:
      - app
    build: ./articles-app
    container_name: laravel-app-c
    env_file:
      - ./articles-app/.env
    ports:
      - 8000:8000
    depends_on:
      - db
    volumes:
      - ./articles-app:/app/articles-app
      - /app/articles-app/vendor

  vite-react-app:
    networks:
      - app
    tty: true
    container_name: vite-react-app-c
    build: ./articles-challenge-frontend
    ports:
      - 3000:3000
    env_file:
      - ./articles-challenge-frontend/.env
    volumes:
      - ./articles-challenge-frontend:/app/articles-challenge-frontend
      - /app/articles-challenge-frontend/node_modules
    depends_on:
      - laravel-app

networks:
  app:
    driver: bridge

volumes:
  db-data:
