version: '3.8'

services:
  laravel-app:
    restart: unless-stopped
    networks:
      - app
      - db
    build:
      context: ./articles-app
      dockerfile: Dockerfile
    environment:
      - MYSQL_DATABASE=articles
      - MYSQL_ROOT_PASSWORD=asd3311062
      - MYSQL_PASSWORD=asd3311062
      - MYSQL_USER=root

    depends_on:
      - db
    ports:
      - 8000:8000
    volumes:
      - '/Users/yossefsherif/Desktop/Work/Articles/articles-app:/app/articles-app'

  vite-react-app:
    networks:
      - app
    tty: true
    build:
      context: ./articles-challenge-frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - '/Users/yossefsherif/Desktop/Work/Articles/articles-challenge-frontend:/app/articles-challenge-frontend'
    depends_on:
      - laravel-app

  db:
    image: mysql:8.0
    restart: unless-stopped
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=articles
      - MYSQL_ROOT_PASSWORD=asd3311062
      - MYSQL_PASSWORD=asd3311062
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - app
      - db

networks:
  app:
    driver: bridge
  db:

volumes:
  db-data: