version: '3.8'

services:
  laravel-app:
    restart: unless-stopped
    networks:
      - app
      - db
    build: ./articles-app
    container_name: laravel-app-c
    environment:
      - MYSQL_DATABASE=articles
      - MYSQL_ROOT_PASSWORD=asd3311062
      - MYSQL_PASSWORD=asd3311062
      - MYSQL_USER=root
      - DB_PORT=3307

    depends_on:
      - db
    ports:
      - '8000:8000'
    volumes:
      - ./articles-app:/app/articles-app
      - /app/articles-app/vendor
    command: ["php", "artisan", "migrate"]

  vite-react-app:
    networks:
      - app
    tty: true
    container_name: vite-react-app-c
    build: ./articles-challenge-frontend
    ports:
      - '3000:3000'
    volumes:
      - ./articles-challenge-frontend:/app/articles-challenge-frontend'
      - /app/articles-challenge-frontend/node_modules
    depends_on:
      - laravel-app

  db:
    image: mysql:8.0
    restart: unless-stopped
    ports:
      - 3307:3306
    environment:
      - MYSQL_DATABASE=articles
      - MYSQL_ROOT_PASSWORD=asd3311062
      - MYSQL_PASSWORD=asd3311062
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - app
      - db

networks:
  app:
    driver: bridge
  db:

volumes:
  db-data: